### ISSUE TITLE
Doubt in Calculator.java file

### ISSUE THREAD

**Issue by ankush2204** [fedelopez/antlr101#1]
In the Calculator.java file (antlr101/src/main/java/cat/pseudocodi/antlr101/Calculator.java),
Line 13 : ParseTree tree = parser.expression();
This is throwing an error while running locally. Can you please suggest appropriate solutions?

**Comment by fedelopez** [comment]
I have pushed a fix for the maven execution. Ensure you have Maven 3 and run the following command:
`mvn test`
This will generate the visitor classes and run all the tests.
If you want to see the AST, execute this command:
`mvn exec:java -Dexec.mainClass="cat.pseudocodi.antlr101.TreeUI"`

**Comment by ankush2204** [comment]
Thank you so much, it works now!!
